### ISSUE TITLE
Crashes without BMI1 | BMI2 | AVX2 | LZCNT

### ISSUE THREAD

**Issue by Marcin-Kozyra** [terra-rebels/classic#37]
if the processor does not have one of these features: 
BMI1 | BMI2 | AVX2 | LZCNT
than the failback routine is not called, instead the whole call is silently dropped.

It seems to only happen if there are invalid transactions in the block. It will sync fine from  from zero, without snapshots, until process is restarted.

Failed to process committed block (10776312:896783285AEFA81E3FC86175181DC6B1ECEC26B2A87D5EB39D7113D6BD65C638): wrong Block.Header.AppHash.  Expected 19FE904AC6A7ABD3518F8F016E299C81B55D6201DF0767497F226CBE46F1F000, got 9E7793445A89E4EA1D09ED20B0D469F946B5A32C217C5EB500D711D944DA8E18

goroutine 99 [running]:
github.com/tendermint/tendermint/blockchain/v0.(BlockchainReactor).poolRoutine(0xc000643a40, 0x0)
    github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x125a
created by github.com/tendermint/tendermint/blockchain/v0.(BlockchainReactor).OnStart
    github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x7a

**Comment by Marcin-Kozyra** [comment]
![1](https://user-images.githubusercontent.com/1209361/209483929-bae2fbf9-cf8b-453e-8cfc-f3a0d54449d7.png)
![2](https://user-images.githubusercontent.com/1209361/209483930-885dded1-31cc-4c7e-b91c-838106def630.png)
